language: android
compiler:
  - g++
  - clang
before_install:



  - sudo apt-get update -qq
  - sudo apt-get install -qq nasm g++-4.6-multilib gcc-multilib libc6-dev-i386
install: 
script: make -B ENABLE64BIT=Yes OS=android && make test 
